#!/usr/bin/env bash

rm /tmp/source.sh* 2> /dev/null
rm /tmp/dest.sh* 2> /dev/null
SOURCETEMP=/tmp/source.sh.$$
DESTTEMP=/tmp/dest.sh.$$

SOURCE=""
DEST=""
SUDO=""

LANGUAGE=0

function cleanup { rm "$SOURCE"; rm "$DEST"; exit; }

trap cleanup; SIGHUP SIGINT SIGTERM

function core { clear; language; cover; sleep 1s; verify; }

function printer() {

    local RED="\e[31m"; local GREEN="\e[32m"; local YELLOW="\e[33m"
    local RESET="\e[0m"; local MESSAGE_TYPE=""; local MESSAGE=""
    MESSAGE_TYPE="${1}"; POSITION="${2}"; ADDITIONAL="${3}";

	local DICTIONARY_ENG=(
		"Your Operating System is not GNU/Linux, exiting"
		"In this system the binary sudo doesn't exist."
		"The rsync binary is not available in this system, please install"
		"The dialog binary is not available in this system, please install"
		"All dependencies is ok!"
		"The directory \"$ADDITIONAL\" doesn't exist"
		"=============== START RSYNC =============== \n" 
		"Done!\n"
		"You don't have permissions to write the destination or read the source"
		"=============== FAIL =============== \n"
	)

	local DICTIONARY_ESP=(
		"Este sistema no es GNU/Linux, saliendo"
		"En este sistema no existe el binario de superusuario."
		"El ejecutable de rsync, no se encuentra en el sistema, por favor instalalo"
		"EL ejecutable de dialog, no se encuentra en el sistema, por favor instalalo"
		"¡Todo ok!"
		"El directorio \"$ADDITIONAL\" no existe"
		"=============== EMPEZAR RSYNC =============== \n" 
		"Listo!\n"
		"No tienes permisos para escribir el directorio de destino o para leer el origen"
		"=============== FALLA =============== \n"
	)

	if [ "$LANGUAGE" -eq 1 ]; then
		case ${MESSAGE_TYPE} in
			print) echo -e "${DICTIONARY_ENG[$POSITION]}";;
			info) echo -e "[${GREEN}+${RESET}] INFO: ${DICTIONARY_ENG[$POSITION]}";; 
			warn) echo -e "[${YELLOW}*${RESET}] WARNING: ${DICTIONARY_ENG[$POSITION]}";; 
			error) echo -e "[${RED}!${RESET}] ERROR: ${DICTIONARY_ENG[$POSITION]}";;
			*) echo -e "[?] UNKNOWN: ${MESSAGE}";;
		esac
	else 
		case ${MESSAGE_TYPE} in
			print) echo -e "${DICTIONARY_ESP[$POSITION]}";;
			info) echo -e "[${GREEN}+${RESET}] INFO: ${DICTIONARY_ESP[$POSITION]}";; 
			warn) echo -e "[${YELLOW}*${RESET}] ADVERTENCIA: ${DICTIONARY_ESP[$POSITION]}";; 
			error) echo -e "[${RED}!${RESET}] ERROR: ${DICTIONARY_ESP[$POSITION]}";;
			*) echo -e "[?] UNKNOWN: ${MESSAGE}";;
		esac
	fi
    
}

function reader() {

	POSITION="${1}";

	local DICTIONARY_ENG=(
		"Please write your source directory"
		"Please write your destination directory to copy"
		"Press Enter to continue..."
	)

	local DICTIONARY_ESP=(
		"Por favor escriba su directorio de origen"
		"Por favor escriba su directorio de destino"
		"Presione Enter para continuar..."
	)

	if [ "$LANGUAGE" -eq 1 ]; then
		echo "${DICTIONARY_ENG[$POSITION]}"
	else 
		echo "${DICTIONARY_ESP[$POSITION]}"
	fi

}

function commandverify() {
	if ! command -v "$1" &> /dev/null; then return 1; else return 0; fi
}

function language {
		
	echo "Bienvenido / Welcome"
	echo "Please, choose your language / Por favor selecciona tu idioma"
	echo "1) English"
	echo "2) Espanol"
	read -n 1 -r OPTION

	case $OPTION in
		1) LANGUAGE=1;;
		2) LANGUAGE=2;;
		*) exit 1;;
	esac
}

function cover {
	
	echo '                                     `"~>v??*^;rikD&MNBQku*;`                                           '
	echo '                                `!{wQNWWWWWWWWWWWWWWWNWWWWWWNdi^`                                       '
	echo '                              .v9NWWWWNRFmWWWWWWWWWWWWga?vs0pNWWWMw!                                    '
	echo '                            !9WWWWWWU>`>&WWWWWWUH!_JNWWWWWQz  ^EWWWWg|                                  '
	echo '                           _SWWWWWNe: /RWWWWWWNNHBRuyix&WWWWWg2?-"VNWWW6_                               '
	echo '                         "kWWWWWNz. .zNWWWWWWw=, ^NsLQNW**MWWWW&WQJuNWWWNr.                             '
	echo '                       .FNWWWWNu. rL&WWWWWWg!!*;^Jo!*BN0aFx)>|!;;;;;!~\r)xFwaao?|,                      '
	echo '                     .sNWWWWMi` -,#WWWWWWNi"` Siwu UWv  .;^|^;`               .!*lUSF*;                 '
	echo '                    )BWWWWWo.   9NWWWWWW0; ;PvLc*aU&^ |L=-``.;>*=                   ;)wmkL_             '
	echo '                  _QWWWWWq"   .aWWWWWWWs`  rF<>\^gQ, /i   ,;;.  !2                      ,*k0F\`         '
	echo '                 *NWWWWNv   ,/&WWWWWWNr "!SL92l)BU.  ^x   x. L,  I_                        `>P&F;       '
	echo '               `2WWWWWg;    !BWWWWWWD"   .s;!\xNa     /L,   !L`  P,                           .?&gr     '
	echo '              ,QWWWWWS`  >;LWWWWWWWk`_;!\u|  ^Ml        ;~!^,  `iv                              `?Ng^   '
	echo '             ^BWWWWWi   *i7NWWWWWWc "a;;?ii"~NV             `;?},                                 ,9WF  '
	echo '            >WWWWWB!  ` ;8WWWWWWM=  r>`;F/2wNc          .;||!,                                      oW#.'
	echo '           ?WWWWW#"  `2;7NWWWWW&_ =_=u%ir`>Wi                                                        PW6'
	echo '          rWWWWWc   `||>WWWWWWU.  r^?7;!v*W)                                                         ,WW|'
	echo '         ^NWWWB!  ! \jrmWWWWWw  `vL.k*\vkW$>rr*r;`        ;rL{7)>!`                                   mWF'
	echo '        .BWWW$,   ,u. PWWWWW) ,r`)|)!__LWv     `;L"     |s>:```._|JuL                                 qWE'
	echo '        uWWWH` .vi"Fo*WWWWN>   ^v  r*`>W}                                                             &Ws '
	echo '       ;WWWP`  `=*ox_pWWWB; ^)i`9xr,#7W*            .     ,\*`                                       |WW! '
	echo '       SWWD` >LLr^_y*NWWQ"  ,<?P~|iF0W}            ~;   v_ `o;                                      .0WU'
	echo '      ^WW0,.!F2xULFi5WW0` >7vr!!z_`*Wv             `|;;^!,~!`                                      .8W8.'
	echo '      dWN;`>JyrkIr`!NWN! ,uFia!9?*2WI                                                             ;QWD.'
	echo '     =WW7`_S)~Fxv| xWWi ;}drqa=;=uWRNmL,                                                         rWWt`  '
	echo '     DWP`;LiL;}c*rsWW&`,Po_e7L/ =Nc `>oD$aaw%ouic7)*r>=|^^~!;;;;;;;;;;;;;~^\>rvL{JctxiiiiuusoF2kgBS/  '
	echo '    ;WN\\Uy>*rF.,pWWWr-;?J"vov^^Nu         `.,"_;!~^\=>r*v?LL{}Jjjjjjj}}7?vr>\^!;____-""",,,..``    '
	echo '    iW?_**>^;>"~&EeWg=|liv*s!~?NL'
	echo '    wWc*$>*~~L6Ni QW! \Uursx >WJ'
	echo '    2M)o*_F "R0; .Wd~U7,``;*iN>'
	echo '    xWe?vI7cMu`  ,W&>xssr~=PB|'
	echo '    "W% ,cBZ_    `M2l\/i,,QQ,'
	echo '     |U$di_       UBu>i)yBy`'
	echo '                  ^Wx,rDR!'
	echo '                   \ZUl^'
	echo '.oPYo. .oPYo. .pPYo.   .oPYo.                       o   o                 .oPYo.   o              8  o                '
	echo '8  .o8     `8 8        8    8                       8                     8        8              8                   '
	echo '8 .P`8   .oP` 8oPYo.   8      oPYo. .oPYo. .oPYo.  o8P o8 o    o .oPYo.   `Yooo.  o8P o    o .oPYo8 o8 .oPYo. .oPYo.  '
	echo '8.d` 8    `b. 8`  `8   8      8  `` 8oooo8 .oooo8   8   8 Y.  .P 8oooo8       `8   8  8    8 8    8  8 8    8 Yb..   '
	echo '8o`  8     :8 8.  .P   8    8 8     8.     8    8   8   8 `b..d` 8.            8   8  8    8 8    8  8 8    8   `Yb. '
	echo '`YooP` `YooP` `YooP`   `YooP` 8     `Yooo` `YooP8   8   8  `YP`  `Yooo`   `YooP`   8  `YooP` `YooP`  8 `YooP` `YooP. '
	echo ':.....::.....::.....::::.....:..:::::.....::.....:::..::..::...:::.....::::.....:::..::.....::.....::..:.....::.....:'
	echo ':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'
	echo ':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'
}

function verify {

    OPERATING=$(uname -o)
	SELECTOR=""

	if [ "$OPERATING" != "GNU/Linux" ]; then
		clear; printer error 0; exit 1
	fi

	SUDO=
		if [ "$EUID" != "0" ]; then
			if  [ -e /usr/bin/sudo ] || [ -e /bin/sudo ]; then
				SUDO=sudo
			else
				clear; printer error 1; exit 1
			fi
		fi

	SELECTOR="rsync"; commandverify "$SELECTOR"; local res=$?
	if [ $res -eq 1 ]; then clear; printer error 2; exit 1; fi
	SELECTOR="dialog"; commandverify "$SELECTOR"; local res=$?
	if [ $res -eq 1 ]; then clear; printer error 3; exit 1; fi

	printer print 4

	START=$(date +%s)
	CHARS="/-\|"

	while [[ $(($(date +%s) - START)) -lt 2 ]]; do
		for (( i=0; i<${#CHARS}; i++ )); do
			sleep 0.08; echo -en "${CHARS:$i:1}" "\r"
		done
	done

	clear
    sourceaction
}

function validator() {

	RES=$(reader 2)

	if [ "$1" == "source" ]; then
		if [ "$2" != "" ]; then
			if [ -d "$2" ]; then
				SOURCE="$2"; destiaction; return 0
			else
				clear; printer error 5 "$2"
        		read -r -p "$RES"; sourceaction
				return 0
			fi
		else
			exit 0
		fi

	elif [ "$1" == "dest" ]; then
		if [ "$2" != "" ]; then
			if [ -d "$2" ]; then
				DEST="$2"; syncer; return 0
			else
				clear; printer error 5 "$2"
        		read -r -p "$RES"; destiaction
				return 0
			fi
		else
			sourceaction
		fi
	else
		exit 0
	fi
	
}

function sourceaction {

	RES=$(reader 0)

    dialog --title "036 rsyncer" \
    --backtitle "036 Creative Studios" \
    --inputbox "$RES" 8 80 2>"$SOURCETEMP"

    RESPONSE=$?
    DATA=$(<$SOURCETEMP)

    case $RESPONSE in
    0) 
        validator "source" "${DATA}" ;;
    1) 
        clear; exit 0  
        return;;
    255) 
        clear; exit 0
        return;;
    esac

}

function destiaction {

	RESPONSE=0
	DATA=0

	RES=$(reader 1)

	dialog --title "036 rsyncer" \
	--backtitle "036 Creative Studios" \
	--inputbox "$RES" 8 80 2>"$DESTTEMP"

	RESPONSE=$?
	DATA=$(<$DESTTEMP)

	case $RESPONSE in
	0) 
		validator "dest" "${DATA}" ;;
	1) 
		clear; sourceaction break;;
	255) 
		clear; sourceaction break;;
	esac

}

function syncer {

	SOURCEREADY=""
	DESTREADY=""

    if [[ "$SOURCE" =~ .*\/$ ]]; then
        SOURCEREADY="$SOURCE"
    else
        SOURCEREADY="$SOURCE/"
    fi

    if [[ "$DEST" =~ .*\/$ ]]; then
        DESTREADY="$DEST"
    else
        DESTREADY="$DEST/"
    fi

	clear
	printer print 6
	echo "SOURCE: $SOURCEREADY"
	echo -e "DESTINATION: $DESTREADY \n"

	if ! rsync -axHAWXS --numeric-ids --info=progress2 "$SOURCEREADY" "$DESTREADY"; then
		clear
		echo "SOURCE: $SOURCEREADY"
		echo -e "DESTINATION: $DESTREADY \n"
		printer print 8
		if ! $SUDO rsync -axHAWXS --numeric-ids --info=progress2 "$SOURCEREADY" "$DESTREADY"; then
			printer print 9; exit 1
		fi
		echo -e "\n =============== OK =============== \n" 
		printer print 7; exit 0

	fi
	
	echo -e "\n =============== OK =============== \n" 
	printer print 7; exit 0
}

core

[ -f $SOURCETEMP ] && rm $SOURCETEMP
[ -f $DESTTEMP ] && rm $DESTTEMP