#!/bin/sh

mkdir rsyncer_cli/dist
mkdir ext4_optimizer_cli/dist
mkdir usb_manager_cli/dist
cd rsyncer_cli
dart pub get
dart compile exe bin/rsyncer_cli.dart -o rsyncer_cli-arm64
mv rsyncer_cli-arm64 dist
cd ../ext4_optimizer_cli
dart pub get
dart compile exe bin/ext4_optimizer_cli.dart -o ext4_optimizer_cli-arm64
mv ext4_optimizer_cli-arm64 dist
cd ../usb_manager_cli
dart pub get
dart compile exe bin/usb_manager_cli.dart -o usb_manager_cli-arm64
mv usb_manager_cli-arm64 dist