name: ext4_optimizer_cli
description: ext4_optimizer_cli
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  console: ^4.1.0
  dcli: ^1.36.0
  fpdart: ^0.4.0
  get_it: ^7.2.0

dev_dependencies:
  lints: ^2.0.1