name: ext4_optimizer_cli
description: ext4_optimizer_cli
version: 1.0.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  console: ^4.1.0
  dcli: ^2.2.2
  fpdart: ^0.6.0

dev_dependencies:
  lints: ^2.1.0