name: efitoggler_gui
description: efitoggler_gui

version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.10
  fpdart: ^1.1.0
  macos_ui: ^2.0.0
  niku: ^2.4.2
  shared_preferences: ^2.2.1

dependency_overrides:
  file: 7.0.0
  win32: 5.0.6

dev_dependencies:
  flutter_lints: ^2.0.3
  icons_launcher: ^2.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/
