name: efitoggler_gui
description: efitoggler_gui

version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  fpdart: ^1.1.0
  macos_ui: ^2.0.5
  niku: ^2.4.3
  shared_preferences: ^2.2.2
  zerothreesix_dart: ^0.1.2

dependency_overrides:
  file: 7.0.0
  win32: 5.0.6

dev_dependencies:
  flutter_lints: ^3.0.1
  icons_launcher: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/
