name: usb_manager_cli
description: usb_manager_cli
version: 1.0.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  console: ^4.1.0
  dcli: ^3.0.2
  fpdart: ^1.1.0
  zerothreesix_dart: ^0.0.6

dev_dependencies:
  lints: ^3.0.0
