#!/usr/bin/env bash

if [ "$(id -u)" -ne 0 ]; then
	echo "ERROR: You need to be root."
	exit 1
fi

rm /tmp/diskenvtemp.sh* 2> /dev/null
rm /tmp/diskmenutemp.sh* 2> /dev/null
rm /tmp/rootpartmenutemp.sh* 2> /dev/null
rm /tmp/swapppartmenutemp.sh* 2> /dev/null
rm /tmp/localestemp.sh* 2> /dev/null
rm /tmp/hosttemp.sh* 2> /dev/null
rm /tmp/graphicaltemp.sh* 2> /dev/null
rm /tmp/driverstemp.sh* 2> /dev/null

DISKMENUTEMP=/tmp/diskmenutemp.sh.$$	
DISKENVTEMP=/tmp/diskenvtemp.sh.$$	
ROOTPARTMENUTEMP=/tmp/rootpartmenutemp.sh.$$	
SWAPPARTMENUTEMP=/tmp/swapppartmenutemp.sh.$$	
LOCALESTEMP=/tmp/localestemp.sh.$$
HOSTTEMP=/tmp/hosttemp.sh.$$
GRAPHICALTEMP=/tmp/graphicaltemp.sh.$$
DRIVERSTEMP=/tmp/driverstemp.sh.$$

function cleanup { rm $DISKENVTEMP; rm $DISKMENUTEMP; rm $ROOTPARTMENUTEMP; 
	rm $SWAPPARTMENUTEMP; rm $LOCALESTEMP; $HOSTTEMP; $GRAPHICALTEMP; $DRIVERSTEMP; exit; }

trap cleanup &> /dev/null; SIGHUP SIGINT SIGTERM &> /dev/null

DISKENVIRONMENT=""
DISK=""
ROOTPART=""
EFIPART=""
SWAPPART=""
SUDOUSER=""

function corelive { clear; cover; sleep 1s; verify; diskenv; }
function corechroot { debian; configurator; hostnamer; localer; newuser; swapper; xanmod; graphical; ohmyzsh; optimizations; software; finisher; }

function cover {
	echo '          					    ``...`                                                    '
	echo '                                      `..:/+++/--/shdmmmmmhy+:.`                                              '
	echo '                                  `-+ydmMMMMMMMMMMMMMMMMMMMMMMNds:`                                           '
	echo '                               `/ymMMMMMNmNMMMMMMMMMMMMNhooyNNMMMMmy:`                                        '
	echo '                             -yNMMMMMNy//hMMMMMMMNyymMMMMNdhm-:sNMMMMd/                                       '
	echo '                           .yMMMMMMNo.`oMMMMMMMMod: .ydMMMMMM+.``omMMMMh.                                     '
	echo '                         `oNMMMMMMo` -MMMMMMMMMmdmMNNmyNMMMMMMMNy/`oNMMMN/                                    '
	echo '                        /mMMMMMMs.  oMMMMMMMNo.  :Mo:hMMs:mMMMMNMMmyhMMMMMo-`                                  '
	echo '                      -hMMMMMMy. .sdMMMMMMMh.o/-/sy:+NMNhys+/:-......--:/+oshddyo/-`                           '
	echo '                    `sNMMMMMh: ` +MMMMMMMMo` .dshs yMh.` `.-..               ``-/oydds/.                       '
	echo '                   /mMMMMMm/`  odMMMMMMMm- s::ydomsMy``+o+:-:/++/`                 `./sdds/.                   '
	echo '                 `yMMMMMMs`   -mMMMMMMMh.  +y+/:-hMs `h-       `:y.                    `.+hmh+.               '
	echo '                -dMMMMMm:  `.:NMMMMMMMs` ./hyso/dMo  :y   //:/-  :y                        ./hmh/`            '
	echo '               :mMMMMMd.   `+NMMMMMMN+ .-ohyyhhhMo   `h.  :: `y   N                           .odmo.           '
	echo '              +NMMMMMy`  `./NMMMMMMN/   `+/-:/yMo     .o:.`.-+-  -d                             `/dNs.        '
	echo '             oMMMMMMs`  o-+MMMMMMMN:`::/oo-  +Ms        -----`  -y-                               `oNm/       '
	echo '           `sMMMMMMo   +yoNMMMMMMm-`o/`-oyh`+Ms          `````-oo`                                  -dMy`     '
	echo '          `yMMMMMN/    /yNMMMMMMd. -h--h+-ysMy          `-////:`                                     `dMh`    '
	echo '          yMMMMMN:  -+:oMMMMMMMd````y++o++sNh`                                                        `mMy    '
	echo '        /MMMMMy`   /+ooMMMMMMh`  ./+N:-+oNm`                                                            mMd   '
	echo '       .NMMMMs  `+ +++MMMMMMy   so++s++oNNs+oooo/-       `/oysyyso/.                                    yMM   '
	echo '       dMMMM+    :s `mMMMMMs `o +++o.-:mN.     `-o-     -h+-`   `-/sh+                                  yMM   '
	echo '      /MMMM+  -/o msoMMMMMo   :y `-s-`dN-                            `                                  hMN    '
	echo '      dMMM+   +oooy:mMMMMo ./o`do:+y/yM/                  `:/`                                         `NMh    '
	echo '     /MMMs  --:+s+osMMMM+  :sy/d//+hNM+            `/   .  `:y                                         sMM:    '
	echo '     mMMd` .mss+`hoyMMM+  `./ss++oohMo             .+  `y+/:+:                                        :MMy     '
	echo '    /MMN. o+mhym/yyNMMs  syo+./y. +Ny               -:::. ``                                         :NMd`     '
	echo '    dMM/`-ysoshh.`+MMm``-yhhdohysyMM:                                                               /NMd.      '
	echo '   :MMy.-sd:oy+y.`dMM/ :od+dhs./oNmmNh/.                                                          `oMMs`      '
	echo '   yMN.-/oy.+yys-hMMd -hy:yy+o `dm.`/ymdyysooo+///::--.......................--::////////+++++oooshNmo   	    '
	echo '  `MMy/+yyosy/-/dMMM/:/ss-oys/`dN-    `.--:://++ooosssyyyyyhyyyyhhhhhhhyyyhyyyssoo++++++///////::::-`         '
	echo '  +Mm`.+dy+sy.-mmNMm`.oys/yyo+hN:                                                                             '
	echo '  yMo/m+.`.-o/Nd-MMo+hho:oh``yM/                                                                               '
	echo '  hMd+ysy+:/yMy`:Mm :+ysoo+ yM/                                                                                '
	echo '  yM/h+-h``hMo  +My+d:`- :syM+                                                                                '
	echo '  oMds+ms+Nm-   +Mm/yyd//:hM/                                                                                  '
	echo '  -Mh  :dNs`    /Mod+:h``dN:                                                                                  	'
	echo '   oNdmms.      -Mmhody/mm-                                                                                    '
	echo '    .--`         mN. -yMy.                                                                                     '
	echo '                  /Nhsmd/                                                                                       '
	echo '                  -/+-`                     '
	echo '.oPYo. .oPYo. .pPYo.   .oPYo.                       o   o                 .oPYo.   o              8  o                '
	echo '8  .o8     `8 8        8    8                       8                     8        8              8                   '
	echo '8 .P`8   .oP` 8oPYo.   8      oPYo. .oPYo. .oPYo.  o8P o8 o    o .oPYo.   `Yooo.  o8P o    o .oPYo8 o8 .oPYo. .oPYo.  '
	echo '8.d` 8    `b. 8`  `8   8      8  `` 8oooo8 .oooo8   8   8 Y.  .P 8oooo8       `8   8  8    8 8    8  8 8    8 Yb..   '
	echo '8o`  8     :8 8.  .P   8    8 8     8.     8    8   8   8 `b..d` 8.            8   8  8    8 8    8  8 8    8   `Yb. '
	echo '`YooP` `YooP` `YooP`   `YooP` 8     `Yooo` `YooP8   8   8  `YP`  `Yooo`   `YooP`   8  `YooP` `YooP`  8 `YooP` `YooP. '
	echo ':.....::.....::.....::::.....:..:::::.....::.....:::..::..::...:::.....::::.....:::..::.....::.....::..:.....::.....:'
	echo ':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'
	echo ':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'
}

function diskenv {

    dialog --clear --backtitle "036 Creative Studios" --title "Disk Environment" \
		--menu "Please choose your disk type \n" 15 50 4 \
        HDD "Hard Drive Disk" \
		SSD-NVMe "Solid State Disk or NVMe" 2>"${DISKENVTEMP}"

	CHOICE=$(<"${DISKENVTEMP}")
	case $CHOICE in
		HDD) DISKENVIRONMENT="HDD"; disclaimer ;;
        SSD-NVMe) DISKENVIRONMENT="SSD"; disclaimer ;;
		*) clear; exit 0; ;;
	esac

}

function whichverify() {
	stat=$(which "$1" 2>&1)

	if [ "$stat" == "" ]; then
		return 1
	elif [[ "$stat" =~ ^which:* ]]; then 
		return 1
	else
		return 0
	fi
}

function verify {

    ARCH=$(uname -m)
    OPERATING=$(uname -o)
	SELECTOR=""

	if [ "$OPERATING" != "GNU/Linux" ]; then
		clear
		echo 'ERROR: Your Operating System is not GNU/Linux, exiting'
		exit 1
	fi
	
	if [ -d /sys/firmware/efi ]; then
		echo "ready" &> /dev/null
	else
		clear
		echo "ERROR: This scripts only works in UEFI/EFI systems, consider change your PC or check your BIOS"
		exit 1
	fi

    if [ "$ARCH" != "x86_64" ]; then
        echo "ERROR: This script is only intended to run on x86_64 PCs."
        exit 1
    fi

    PING=$(ping -c 1 8.8.8.8 2>&1) 

    if [[ "$PING" =~ unreachable* ]]; then
		clear
		echo "ERROR: This PC doesn't have internet connection, please check"
		exit 1
	fi

	SELECTOR="fsck.f2fs"
	whichverify "$SELECTOR"
	local res=$?
	if [ $res -eq 1 ]; then
        clear
		echo "f2fs-tools is not available in this system, please install it"
		exit 1
	fi

	SELECTOR="dialog"
	whichverify "$SELECTOR"
	local res=$?

	if [ $res -eq 1 ]; then
        clear
		echo "dialog is not available in this system, please install it"
		exit 1
	fi

    SELECTOR="debootstrap"
	whichverify "$SELECTOR"
	local res=$?

	if [ $res -eq 1 ]; then
		clear
		echo "debootstrap is not available in this system, please install it"
		exit 1
	fi

	echo "All dependencies is ok!"

	START=$(date +%s)
	CHARS="/-\|"

	while [[ $(($(date +%s) - START)) -lt 2 ]]; do
		for (( i=0; i<${#CHARS}; i++ )); do
			sleep 0.08
			echo -en "${CHARS:$i:1}" "\r"
		done
	done

}

function disclaimer {
	clear
	dialog --msgbox "DANGER!!!: Your destination device would be formatted and empty, formatting always cause data loss, PLEASE backup all your data before start" 8 70

	if [ "$DISKENVIRONMENT" == "HDD" ] ; then
		dialog --msgbox "Before installing, we recomend that your disk has the next partition scheme, before install\n\n\
		GPT -> \n \
		1.	/dev/sdX1	EFI			200MB		fat32		esp\n\
		2.	/dev/sdX2	debian  	>20GB		ext4		primary\n\
		3.	/dev/sdx3	linux-swap	2GB-4GB		swap		primary\n\n\

		GNU Parted script example  for format a 20GB disk\n\n \

		mklabel gpt \ \n \
		mkpart EFI fat32 1MiB 200MiB \ \n \
		set 1 esp on \ \n \
		mkpart ROOT ext4 200MiB 19.0GiB \ \n \
		mkpart SWAP linux-swap 19.0GiB 100% \ \n" 20 70

	elif [ "$DISKENVIRONMENT" == "SSD" ]; then
	dialog --msgbox "Before installing, we recomend that your disk has the next partition scheme, before install\n\n\
		GPT -> \n \
		1.	/dev/sdX1	EFI			200MB		fat32		esp\n\
		2.	/dev/sdX2	debian	>20GB		f2fs/ext4		primary\n\

		GNU Parted script example for format a 20GB disk\n\n \

		mklabel gpt \ \n \
		mkpart EFI fat32 1MiB 200MiB \ \n \
		set 1 esp on \ \n \
		mkpart ROOT f2fs 200MiB 100% \ \n" 20 70
	fi
	diskmenu

}

function diskverify() {

	clear
	LABEL=$(blkid -o value -s PTTYPE "$1")
	EFI=""
	EFIORDER=""
	BLOCK=""

	if [ "$LABEL" == "dos" ]; then
		echo "ERROR: The device has a DOS Label Type (MBR), this script only works with gpt"
		exit 1
	fi

	if [[ $1 =~ sd[[:alpha:]] ]]; then

		EFI=$(fdisk -l "$1" | sed -ne '/EFI/p')
		EFIORDER=$(echo "$EFI" | sed -ne '/[[:alpha:]]1/p' )

		if [ "$DISKENVIRONMENT" == "SSD" ]; then
			BLOCK=$(echo "$1" | cut -d "/" -f3)
			ROTATIONAL="$(cat /sys/block/"$BLOCK"/queue/rotational)"

			if  [ "$ROTATIONAL" == "1" ]; then
				echo "ERROR: You choose a SSD device, but this device is rotational, if is that not the case, that device is USB"
				exit 1
			fi

		elif [ "$DISKENVIRONMENT" == "HDD" ]; then
		
			BLOCK=$(echo "$1" | cut -d "/" -f3)
			ROTATIONAL="$(cat /sys/block/"$BLOCK"/queue/rotational)"

			if  [ "$ROTATIONAL" == "0" ]; then
				echo "ERROR: ou choose a HDD device, but this device is not rotational, please check and run this script again"
				exit 1
			fi
		fi

		if [ "$EFI" == "" ]; then
			echo "ERROR: The device doesn't have a EFI partition"
			exit 1
		fi
		if [ "$EFIORDER" == "" ]; then
			echo "ERROR: The device has the EFI partition in other side than $1 1"
			exit 1
		fi

		DISK=$1
		rootpartmenu

	elif [[ $1 =~ mmcblk[[:digit:]] ]]; then

		EFI=$(fdisk -l "$1" | sed -ne '/EFI/p')
		EFIORDER=$(echo "$EFI" | sed -ne '/p1/p' )

		if [ "$DISKENVIRONMENT" == "HDD" ]; then
			echo "ERROR: You choose a HDD device, but this device is not rotational, please check and run this script again"
			exit 1
		fi

		if [ "$EFI" == "" ]; then
			echo "ERROR: The device doesn't have a EFI partition"
			exit 1
		fi
		if [ "$EFIORDER" == "" ]; then
			echo "ERROR: The device has the EFI partition in other side than $1 1"
			exit 1
		fi

		DISK=$1
		rootpartmenu

	elif [[ $1 =~ nvme[[:digit:]] ]]; then

		EFI=$(fdisk -l "$1" | sed -ne '/EFI/p')
		EFIORDER=$(echo "$EFI" | sed -ne '/p1/p' )

		if [ "$DISKENVIRONMENT" == "HDD" ]; then
			echo "ERROR: You choose a HDD device, but this device is not rotational, please check and run this script again"
			exit 1
		fi

		if [ "$EFI" == "" ]; then
			echo "ERROR: The device doesn't have a EFI partition"
			exit 1
		fi
		if [ "$EFIORDER" == "" ]; then
			echo "ERROR: The device has the EFI partition in other side than $1 1"
			exit 1
		fi

		DISK=$1
		rootpartmenu

	fi

}

function diskmenu {

	clear
	COUNT=0
	BLOCK=()
	DIRTYDEVS=()

	DEVICES=$(find /dev/disk/by-path/ | sed 's/^\/dev\/disk\/by-path\///') # 3.0_high_speed_000000123AFF-0:0 ...

	for DEVICE in $DEVICES; do
		DIRTYDEVS[$COUNT]=$(readlink "/dev/disk/by-path/$DEVICE") # ../../sda ../../sda1 ... 
		COUNT=$(( COUNT + 1 ))
	done

	if [ $COUNT -eq 0 ]; then
		clear
		echo "FATAL ERROR: There's not disks available in your system, please verify!!!"
		exit 1
	fi

	COUNT=0

	for DEV in "${DIRTYDEVS[@]}"; do	

		ABSOLUTEPARTS=$(echo "$DEV" | sed 's/^\.\.\/\.\.\//\/dev\//' | sed '/.*[[:alpha:]]$/d' | sed '/blk[[:digit:]]$/d' | sed '/nvme[[:digit:]]n[[:digit:]]$/d') #/dev/sda1 /dev/sda2 ...

		if [ "$ABSOLUTEPARTS" == "" ]; then
			BLOCK[$BLOCKCOUNT]=$(echo "$DEV" | sed 's/^\.\.\/\.\.\///') #sda sdb
			BLOCKCOUNT=$(( BLOCKCOUNT + 1 ))
		fi
		
	done

	COUNT=0
	MODEL=0
	DEVICE=0
	ARRAY=()

	for PART in "${BLOCK[@]}"; do
		DEVICE="/dev/$PART"
		BLOCKSTAT="${BLOCK[$COUNT]}"
		SIZE=$(lsblk -no SIZE /dev/"$PART" | head -1 | sed s/..//)
		MODEL="$(cat /sys/class/block/"$BLOCKSTAT"/device/model)" #KINGSTON 
		ARRAY+=("$DEVICE" "$MODEL $SIZE")
		COUNT=$(( COUNT + 1 ))
	done

		dialog --clear --backtitle "036 Creative Studios" --title "Choose a device" \
		--menu "Choose a device for install"\
		15 50 4 "${ARRAY[@]}" 2>"${DISKMENUTEMP}"

	CHOICE=$(<"${DISKMENUTEMP}")

	case $CHOICE in
		"$CHOICE") diskverify "$CHOICE";;
		*) clear; exit 0;;
	esac
}

function rootpartmenu {
	#Menu para seleccionar la particion de raiz de arch
	VERIFY=""
	TYPE=""
	COUNT=0
	COUNTMOUNT=0
	ISMOUNTED=0
	ROOTPARTS=()

	EFIPART=$(fdisk -l "$DISK" | sed -ne /EFI/p | cut -d " " -f1)

	if [[ $DISK =~ sd[[:alpha:]] ]]; then
		VERIFY=$(find "$DISK"* | sed '/[[:alpha:]]$/d')
	elif [[ $DISK =~ mmcblk[[:digit:]] ]]; then
		VERIFY=$(find "$DISK"* | sed '/k[[:digit:]]$/d')
	elif [[ $DISK =~ nvme[[:digit:]]n[[:digit:]] ]]; then
		VERIFY=$(find "$DISK"* | sed '/e[[:digit:]]n[[:digit:]]$/d')
	fi

	for PART in $VERIFY; do

	if [ "$PART" != "$EFIPART" ]; then

		ISMOUNTED=$(lsblk "$PART" | sed -ne '/\//p')
		if [ "$ISMOUNTED" != "" ]; then
			COUNTMOUNT=$(( COUNTMOUNT + 1 ))
		else
			ROOTPARTS+=("$PART" "$TYPE")
		fi
		COUNT=$((COUNT + 1))

	fi

	done

	if [ "$COUNTMOUNT" -eq $COUNT ]; then
		clear
		echo "ERROR: All the partitions of the device are mounted in your system, please unmount the desired partition"
		exit 1
	fi

	dialog --clear --backtitle "036 Creative Studios" --title "Select a root partition" \
		--menu "Please select a partition \n" 15 50 4 "${ROOTPARTS[@]}" 2>"${ROOTPARTMENUTEMP}"

	CHOICE=$(<"${ROOTPARTMENUTEMP}")
	case $CHOICE in
		"$CHOICE") ROOTPART="$CHOICE"; swapmenu "$CHOICE" ;;
		*) clear; exit 0; ;;
	esac
}

function swapmenu() {

	if [ "$1" == "" ]; then
		clear
		exit 0
	fi

	if [ $DISKENVIRONMENT == "HDD" ]; then

		VERIFY=""
		TYPE=""
		COUNT=0
		COUNTMOUNT=0
		ISMOUNTED=0
		SWAPPARTS=()

		if [[ $DISK =~ sd[[:alpha:]] ]]; then
			VERIFY=$(find "$DISK"* | sed '/[[:alpha:]]$/d')
		elif [[ $DISK =~ mmcblk[[:digit:]] ]]; then
			VERIFY=$(find "$DISK"* | sed '/k[[:digit:]]$/d')
		elif [[ $DISK =~ nvme[[:alpha:]] ]]; then
			VERIFY=$(find "$DISK"* | sed '/e[[:digit:]]$/d')
		fi

		for PART in $VERIFY; do

		if [ "$PART" != "$EFIPART" ]; then

			if [ "$PART" != "$ROOTPART" ]; then

				ISMOUNTED=$(lsblk "$PART" | sed -ne '/\//p')
				if [ "$ISMOUNTED" != "" ]; then
					COUNTMOUNT=$(( COUNTMOUNT + 1 ))
				else
					SWAPPARTS+=("$PART" "$TYPE")
				fi
					COUNT=$((COUNT + 1))
			fi

		fi

		done

		if [ "$COUNTMOUNT" -eq $COUNT ]; then
			clear
			echo "ERROR: All the partitions of the device are mounted in your system, please unmount the desired partition"
			exit 1
		fi

		dialog --clear --backtitle "036 Creative Studios" --title "Select a swap partition" \
			--menu "Please select a swap partition \n" 15 50 4 "${SWAPPARTS[@]}" 2>"${SWAPPARTMENUTEMP}"

		CHOICE=$(<"${SWAPPARTMENUTEMP}")
		case $CHOICE in
			"$CHOICE") SWAPPART="$CHOICE"; diskformat "$CHOICE" ;;
			*) clear; exit 0; ;;
		esac

	elif [ $DISKENVIRONMENT == "SSD" ]; then
		diskformat "pass"
	fi

}

function diskformat {

	if [ "$1" == "" ]; then
		clear
		exit 0
	fi

	if [ $DISKENVIRONMENT == "HDD" ]; then
		dialog --title "DANGER ZONE!!!" --backtitle "036 Creative Studios" \
			--yesno "This partitions will be format Continue? \n$EFIPART (EFI) \n$ROOTPART (ROOT) \n$SWAPPART (SWAP)" 8 60
	elif [ $DISKENVIRONMENT == "SSD" ]; then
		dialog --title "DANGER ZONE!!!" --backtitle "036 Creative Studios" \
			--yesno "This partitions will be format Continue? \n$EFIPART (EFI) \n$ROOTPART (ROOT)" 7 60
	fi

	clear
	response=$?

	if [ $response = 0 ]; then

		if [ $DISKENVIRONMENT == "HDD" ]; then

			echo -e "=============== FORMAT ROOT FILESYSTEM AND SWAP =============== \n" 

			mkfs.ext4 "$ROOTPART"
			mkswap "$SWAPPART"
			swapon "$SWAPPART"

			echo " "
			echo -e "=============== OK =============== \n" 
			read -r -p "Press Enter to continue..."
			clear
	
		elif [ $DISKENVIRONMENT == "SSD" ]; then

			echo -e "=============== FORMAT ROOT FILESYSTEM =============== \n" 

			mkfs.f2fs -f "$ROOTPART"

			echo " "
			echo -e "=============== OK =============== \n" 
			read -r -p "Press Enter to continue..."
			clear
	
		fi

		echo -e "=============== FORMAT EFI AND MOUNT =============== \n" 

		mkfs.fat -F32 "$EFIPART"
		mount "$ROOTPART" /mnt
        mkdir /mnt/boot
		mkdir /mnt/boot/efi
		mount "$EFIPART" /mnt/boot/efi

		echo " "
		echo -e "=============== OK =============== \n" 
		read -r -p "Press Enter to continue..."
		clear

		debootstraper


	elif [ $response -eq 1 ] || [ $response -eq 255 ]; then
		clear
		exit 0
	else
		clear
		exit 0
	fi
	
}

function unmounter {
	clear

	if [ $DISKENVIRONMENT == "HDD" ]; then
		umount /mnt/proc/
		umount /mnt/sys/
		umount /mnt/dev/
		umount "$ROOTPART"
		swapoff "$SWAPPART"
	elif [ $DISKENVIRONMENT == "SSD" ]; then
		umount "$ROOTPART"
	fi
	echo "unmounted filesystems succesfully"
	exit 0
}

function debootstraper {

	echo -e "=============== DEBOOTSTRAP: INSTALL DEBIAN SID CORE =============== \n" 
	
	debootstrap --arch amd64 sid /mnt https://deb.debian.org/debian/
    mount -t proc /proc /mnt/proc/
    mount -t sysfs /sys /mnt/sys/
    mount -o bind /dev /mnt/dev/

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."

	toggler
}

function toggler {

	cp "$0" /mnt/deb-setupper.sh
    chroot /mnt /bin/bash ./deb-setupper.sh chroot $DISKENVIRONMENT "$EFIPART" "$ROOTPART" "$SWAPPART"

	unmounter

	exit 0
}

function debian {

	clear

	echo -e "=============== DEBIAN: UPDATE SID REPOSITORIES =============== \n" 	

	echo "deb http://deb.debian.org/debian sid main contrib non-free" > /etc/apt/sources.list
	echo "deb-src http://deb.debian.org/debian sid main contrib non-free" >> /etc/apt/sources.list

	apt update

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."
	clear

	echo -e "=============== INSTALL CORE PACKAGES =============== \n" 

	apt install -y sudo locales git wget aptitude grub-efi-amd64 vim \
		grub-efi efibootmgr net-tools network-manager-gnome dialog \
		openssh-server python rsync screen unrar p7zip zsh linux-image-amd64 \
		firmware-linux firmware-linux-free firmware-linux-nonfree util-linux gnupg

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."
	clear

}

function configurator {

	dialog --title "Laptop" --backtitle "036 Creative Studios" \
        --yesno "This PC is a Laptop?" 8 60

	response=$?

	if [ $response = 0 ]; then
		clear
		tasksel install laptop
	fi

	clear

	echo -e "=============== GENERATE FSTAB AND ROOT PASSWORD FOR YOUR SYSTEM =============== \n" 

	
	SDA1=$(/usr/sbin/blkid -s UUID -o value "$EFIPART")
	SDA2=$(/usr/sbin/blkid -s UUID -o value "$ROOTPART")

	if [ $DISKENVIRONMENT == "HDD" ]; then
		SDA3=$(/usr/sbin/blkid -s UUID -o value "$SWAPPART")
		{
			echo "UUID=$SDA2          /             ext4      defaults              1      1"
			echo "UUID=$SDA1          /boot/efi     vfat      defaults              0      0"
			echo "UUID=$SDA3          none          swap      sw                    0      0"
		} > /etc/fstab

	elif [ $DISKENVIRONMENT == "SSD" ]; then
		{
			echo "UUID=$SDA2          /             f2fs      discard               1      1"
			echo "UUID=$SDA1          /boot/efi     		vfat      defaults              0      0"
		} > /etc/fstab
	fi

	passwd

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."

	clear

	echo -e "=============== CONFIGURE GRUB =============== \n" 

	/usr/sbin/grub-install --target=x86_64-efi \
		--boot-directory=/boot --efi-directory=/boot/efi --bootloader-id=GRUB
	/usr/sbin/grub-mkconfig -o /boot/grub/grub.cfg
	umount /boot/efi

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."

	clear

	echo -e "=============== START NETWORKMANAGER AND SSH SERVICES =============== \n" 

	systemctl enable NetworkManager &> /dev/null
	systemctl enable ssh &> /dev/null
	sed -i 's/^#PermitRootLogin\s.*$/PermitRootLogin Yes/' \
		/etc/ssh/sshd_config &> /dev/null

	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."

}

function hostnamer {

	clear
	dialog --title "Hostname" \
    --backtitle "036 Creative Studios" \
    --inputbox "Please write your hostname (ex: A036-debian)" 8 80 2>"$HOSTTEMP"

    RESPONSE=$?
    DATA=$(<$HOSTTEMP)

    case $RESPONSE in
    0) 
		echo "${DATA}" > /etc/hostname
		echo "127.0.1.1        ${DATA}" >> /etc/hosts
		return;;
    1) 
        clear; exit 0  
        return;;
    255) 
        clear; exit 0
        return;;
    esac
	
}

function localer {

	clear
	dialog --msgbox "America/Guayaquil is the timezone by default, if you want to change, here is the command\n\n \
		ln -sf /usr/share/zoneinfo/REGION/CITY /etc/localtime" 9 50

	ln -sf /usr/share/zoneinfo/America/Guayaquil /etc/localtime
	hwclock --systohc

	dialog --clear --backtitle "036 Creative Studios" \
		--title "Locale" \
		--menu "Choose your locale, if you want to change to other locales, check the README of the Github of this project" 12 50 4 \
		Spanish "es_ES" \
		English "en_US" 2>"${LOCALESTEMP}"

		menuitem=$(<"${LOCALESTEMP}")

		case $menuitem in
			Spanish) 
				clear
				sed -i 's/^# es_ES.UTF-8 UTF-8/es_ES.UTF-8 UTF-8/' /etc/locale.gen &> /dev/null

				echo 'LANG="es_ES.UTF-8"' >/etc/default/locale
				echo 'LC_TIME="es_ES.UTF-8"' >> /etc/default/locale
				echo 'LANGUAGE="es_EC:es_ES:es"' >> /etc/default/locale
				return;;
			English) 
				clear
				sed -i 's/^# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen &> /dev/null
				locale-gen
				echo 'LANG="en_US.UTF-8"' > /etc/locale.conf
				echo 'LC_TIME="en_US.UTF-8"' >> /etc/locale.conf
				echo 'LANGUAGE="es_US:en"' >> /etc/locale.conf
				return;;
			*) clear; exit 0;;
		esac
}

function newuser {

	clear
	echo -e "=============== ADD A USER TO A SUDO GROUP =============== \n" 
	
	read -r -p "Write your new user: " SUDOUSER
	/usr/sbin/adduser "$SUDOUSER"
	/usr/sbin/usermod -aG sudo "$SUDOUSER"

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."
}

function swapper {

	clear
	echo -e "=============== SWAPPING =============== \n" 

	if [ $DISKENVIRONMENT == "HDD" ]; then

		echo "vm.swappiness=60" >> /etc/sysctl.conf

	elif [ $DISKENVIRONMENT == "SSD" ]; then
		dd if=/dev/zero of=/swapfile bs=1M count=1024 status=progress
		chmod 600 /swapfile
		mkswap /swapfile
		swapon /swapfile
		echo "swapfile none swap defaults 0 0" >> /etc/fstab
		echo "vm.swappiness=1" >> /etc/sysctl.conf
	fi

	
	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."


}

function xanmod {

	clear
	echo -e "=============== XANMOD KERNEL =============== \n" 
	
	echo 'deb http://deb.xanmod.org releases main' | tee /etc/apt/sources.list.d/xanmod-kernel.list
	wget -qO - https://dl.xanmod.org/gpg.key | apt-key --keyring /etc/apt/trusted.gpg.d/xanmod-kernel.gpg add -
	apt update && apt install linux-xanmod -y
	apt remove linux-image-amd64 -y

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."
}

function graphical {

	clear
	dialog --clear --title "Graphical Environment" \
	--backtitle "036 Creative Studios" \
	--menu "Choose a GUI, these are the common used, this script recommends XFCE" 15 50 4 \
			XFCE "Xfce Desktop Environment" \
			GNOME "GNOME Desktop Environment" \
			KDE "KDE Desktop Environment" \
			XORG "Minimal xorg Desktop" \
			CUTEFISH "Cutefish Desktop (Beta)" \
			NOGUI "No install GUI" 2>"${GRAPHICALTEMP}"

	menuitem=$(<"${GRAPHICALTEMP}")

		case $menuitem in
			XFCE) 

				clear
				echo -e "=============== XFCE =============== \n" 
	
			apt install -y xserver-xorg xfce4 xfce4-goodies xfce4-indicator-plugin \
				ttf-ubuntu-font-family firefox gdm3 grub-customizer nemo cinnamon-l10n

				echo " "
				echo -e "=============== OK =============== \n" 
				read -r -p "Press Enter to continue..."
				return;;

			GNOME) 

				clear
				echo -e "=============== GNOME =============== \n" 

			apt install -y task-gnome-desktop \
				ttf-ubuntu-font-family firefox grub-customizer nemo cinnamon-l10n

				echo " "
				echo -e "=============== OK =============== \n" 
				read -r -p "Press Enter to continue..."
				return;;

			KDE) 

			apt install -y task-kde-desktop ttf-ubuntu-font-family firefox \
				grub-customizer nemo cinnamon-l10n

				clear
				echo -e "=============== KDE =============== \n" 
	

				echo " "
				echo -e "=============== OK =============== \n" 
				read -r -p "Press Enter to continue..."
				return;;

			XORG) 

				clear
				echo -e "=============== XORG ONLY =============== \n" 
			apt install -y xserver-xorg

				echo " "
				echo -e "=============== OK =============== \n" 
				read -r -p "Press Enter to continue..."
				return;;

			NOGUI) 
				return;;

			*) clear; exit 0;;
		esac
}

function ohmyzsh {

	clear
	echo -e "=============== OMZ =============== \n" 

	touch /home/"$SUDOUSER"/omz.sh
	{
		sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
		sed -i -e 's/ZSH_THEME=.*/ZSH_THEME=\"pmcgee\"/' .zshrc
		sed -i -e '/^source $ZSH.*/i ZSH_DISABLE_COMPFIX=true' .zshrc
		sudo ln -s "$HOME"/.zshrc /root/.zshrc
		sudo ln -s "$HOME"/.oh-my-zsh /root/.oh-my-zsh
		git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
		git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
		sed -i -e 's/plugins=(.*/plugins=(git zsh-syntax-highlighting zsh-autosuggestions)/' .zshrc
	} > /home/"$SUDOUSER"/omz.sh

	chown "$SUDOUSER" /home/"$SUDOUSER"/omz.sh

	echo "We create a script called omz.sh in your home directory, after reboot, use chmod +x at omz.sh"

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."

}

function optimizations {

	clear
	echo -e "=============== OPTIMIZATIONS =============== \n" 

	sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT=".*"/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=0 nowatchdog"/' \
		/etc/default/grub &> /dev/null
	/usr/sbin/grub-mkconfig -o /boot/grub/grub.cfg
	systemctl mask lvm2-monitor

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."

}

function software {

	dialog --title "More Sofware!!" --backtitle "036 Creative Studios" \
		--yesno "This script has a little pack of software, Do you like it?\n \
			-> gdebi \n \
			-> synaptic \n \
			-> aptitude \n \
			-> libwnck-common \n \
			-> libwnck22 \n \
			-> baobab \n \
			-> hfsutils \n \
			-> hfsprogs \n \
			-> ntfs-3g \n \
			-> exfat-fuse \n \
			-> exfat-utils \n \
			-> gparted \n \
			-> xarchiver \n \
			-> wine \n \
			-> playonlinux  \n \
			-> preload  \n \
			-> xrdp" 26 65
	response=$?
	echo $?

	if [ $response -eq 0 ]; then
	
	clear
	echo -e "=============== SOFTWARE =============== \n" 

	apt install -y gdebi synaptic aptitude libwnck-common \
		libwnck22 baobab hfsutils hfsprogs ntfs-3g \
		exfat-fuse exfat-utils gparted xarchiver wine playonlinux xrdp preload \
		numix-gtk-theme numix-icon-theme-circle
		
	adduser xrdp ssl-cert
	systemctl enable xrdp
	systemctl enable xrdp-sesman
	systemctl enable preload
	systemctl mask lvm2-monitor

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."


	elif [ $response -eq 1 ]; then
		clear
		return
	else
		clear
		exit 0
	fi

}

function finisher {

	clear
	dialog --msgbox 'READY!!!, Your PC is succesfully installed with Debian Sid, if you have errors, please report at 036bootstraper in GitHub' 7 50
	rm -f /deb-setupper.sh &> /dev/null
	clear
	umount /mnt/boot/efi &> /dev/null
	echo "Please reboot and remove your live media"
	exit

}

if [ "$1" == "chroot" ]; then
	DISKENVIRONMENT=$2
	EFIPART=$3
	ROOTPART=$4
	SWAPPART=$5

	corechroot
else
	corelive
fi

[ -f $DISKENVTEMP ] && rm $DISKENVTEMP 
[ -f $DISKMENUTEMP ] && rm $DISKMENUTEMP 
[ -f $ROOTPARTMENUTEMP ] && rm $ROOTPARTMENUTEMP
[ -f $SWAPPARTMENUTEMP ] && rm $SWAPPARTMENUTEMP
[ -f $LOCALESTEMP ] && rm $LOCALESTEMP
[ -f $HOSTTEMP ] && rm $HOSTTEMP
[ -f $GRAPHICALTEMP ] && rm $GRAPHICALTEMP
[ -f $DRIVERSTEMP ] && rm $DRIVERSTEMP