name: ext4_optimizer_gui
description: ext4_optimizer_gui

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  adwaita: ^1.1.0
  bitsdojo_window: ^0.1.6
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_platform_alert: ^0.5.1
  flutter_pty:
    git:
      url: https://github.com/victor7w7r/flutter_pty.git
      ref: main
  flutter_riverpod: ^2.4.9
  fpdart: ^1.1.0
  libadwaita: ^2.0.2
  libadwaita_bitsdojo: ^0.5.5
  niku: ^2.4.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  xterm: ^3.5.0
  zerothreesix_dart: ^0.0.6+11

dependency_overrides:
  win32: ^5.2.0

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
