name: ext4_optimizer_gui
description: ext4_optimizer_gui

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adwaita: ^0.5.2
  bitsdojo_window: ^0.1.5
  dio: ^4.0.6
  flutter_platform_alert: ^0.3.0
  flutter_pty: ^0.3.1
  flutter_riverpod: ^2.1.3
  fpdart: ^0.4.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  libadwaita: ^1.2.5
  libadwaita_bitsdojo: ^0.5.5
  nester: ^1.2.1
  niku: ^2.3.3
  path_provider: ^2.0.12
  riverpod_context: ^0.3.0
  shared_preferences: ^2.0.17
  xterm: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/
