void cover() {
  print('                                    `"~>v??*^;rikD&MNBQku*;`                                           \n'
    '                                `!{wQNWWWWWWWWWWWWWWWNWWWWWWNdi^`                                       \n'
    '                              .v9NWWWWNRFmWWWWWWWWWWWWga?vs0pNWWWMw!                                    \n'
    '                            !9WWWWWWU>`>&WWWWWWUH!_JNWWWWWQz  ^EWWWWg|                                  \n'
    '                           _SWWWWWNe: /RWWWWWWNNHBRuyix&WWWWWg2?-"VNWWW6_                              \n'
    '                         "kWWWWWNz. .zNWWWWWWw=, ^NsLQNW**MWWWW&WQJuNWWWNr.                            \n'
    '                       .FNWWWWNu. rL&WWWWWWg!!*;^Jo!*BN0aFx)>|!;;;;;!~/r)xFwaao?|,                      \n'
    '                     .sNWWWWMi` -,#WWWWWWNi"` Siwu UWv  .;^|^;`               .!*lUSF*;                \n'
    '                    )BWWWWWo.   9NWWWWWW0; ;PvLc*aU&^ |L=-``.;>*=                   ;)wmkL_             \n'
    '                  _QWWWWWq"   .aWWWWWWWs`  rF<>/^gQ, /i   ,;;.  !2                      ,*k0F/`        \n'
    '                 *NWWWWNv   ,/&WWWWWWNr "!SL92l)BU.  ^x   x. L,  I_                        `>P&F;      \n'
    '               `2WWWWWg;    !BWWWWWWD"   .s;!/xNa     /L,   !L`  P,                           .?&gr     \n'
    '              ,QWWWWWS`  >;LWWWWWWWk`_;!/u|  ^Ml        ;~!^,  `iv                              `?Ng^   \n'
    '             ^BWWWWWi   *i7NWWWWWWc "a;;?ii"~NV             `;?},                                 ,9WF  \n'
    '            >WWWWWB!  ` ;8WWWWWWM=  r>`;F/2wNc          .;||!,                                      oW#.\n'
    '           ?WWWWW#"  `2;7NWWWWW&_ =_=u%ir`>Wi                                                        PW6\n'
    '          rWWWWWc   `||>WWWWWWU.  r^?7;!v*W)                                                         ,WW|\n'
    '         ^NWWWB!  ! /jrmWWWWWw  `vL.k*/vkW\$>rr*r;`        ;rL{7)>!`                                   mWF\n'
    '         .BWWW\$,   ,u. PWWWWW) ,r`)|)!__LWv     `;L"     |s>:```._|JuL                                 qWE\n'
    '        uWWWH` .vi"Fo*WWWWN>   ^v  r*`>W}                                                             &Ws \n'
    '        ;WWWP`  `=*ox_pWWWB; ^)i`9xr,#7W*            .     ,/*`                                       |WW!\n'
    '       SWWD` >LLr^_y*NWWQ"  ,<?P~|iF0W}            ~;   v_ `o;                                      .0WU\n'
    '      ^WW0,.!F2xULFi5WW0` >7vr!!z_`*Wv             `|;;^!,~!`                                      .8W8.\n'
    '      dWN;`>JyrkIr`!NWN! ,uFia!9?*2WI                                                             ;QWD.\n'
    '     =WW7`_S)~Fxv| xWWi ;}drqa=;=uWRNmL,                                                         rWWt`\n'
    '     DWP`;LiL;}c*rsWW&`,Po_e7L/ =Nc `>oD\$aawTouic7)*r>=|^^~!;;;;;;;;;;;;;~^/>rvL{JctxiiiiuusoF2kgBS/ \n'
    '    ;WN\\Uy>*rF.,pWWWr-;?J}"vov^^Nu         `.,"_;!~^/=>r*v?LL{}Jjjjjjj}}7?vr>/^!;____-""",,,..``    \n'
    '    iW?_**>^;>"~&EeWg=|liv*s!~?NL\n'
    '    wWc*\$>*~~L6Ni QW! /Uursx >WJ\n'
    '    2M)o*_F "R0; .Wd~U7,``;*iN>\n'
    '    xWe?vI7cMu`  ,W&>xssr~=PB|\n'
    '    "WY ,cBZ_    `M2l//i,,QQ,\n'
    '     |U\$di_       UBu>i)yBy`\n'
    '                  ^Wx,rDR!\n'
    '                   /ZUl^\n'
    '.oPYo. .oPYo. .pPYo.   .oPYo.                       o   o                 .oPYo.   o              8  o                \n'
    '8  .o8     `8 8        8    8                       8                     8        8              8                   \n'
    '8 .P`8   .oP` 8oPYo.   8      oPYo. .oPYo. .oPYo.  o8P o8 o    o .oPYo.   `Yooo.  o8P o    o .oPYo8 o8 .oPYo. .oPYo.  \n'
    '8.d` 8    `b. 8`  `8   8      8  `` 8oooo8 .oooo8   8   8 Y.  .P 8oooo8       `8   8  8    8 8    8  8 8    8 Yb..   \n'
    '8o`  8     :8 8.  .P   8    8 8     8.     8    8   8   8 `b..d` 8.            8   8  8    8 8    8  8 8    8   `Yb. \n'
    '`YooP` `YooP` `YooP`   `YooP` 8     `Yooo` `YooP8   8   8  `YP`  `Yooo`   `YooP`   8  `YooP` `YooP`  8 `YooP` `YooP. \n'
    ':.....::.....::.....::::.....:..:::::.....::.....:::..::..::...:::.....::::.....:::..::.....::.....::..:.....::.....:\n'
    ':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'
  );
}