package lib

import "fmt"

func Cover() {
	Clear()
	fmt.Println("                                    `\"~>v??*^;rikD&MNBQku*;`                                           ")
	fmt.Println("                                `!{wQNWWWWWWWWWWWWWWWNWWWWWWNdi^`                                       ")
	fmt.Println("                              .v9NWWWWNRFmWWWWWWWWWWWWga?vs0pNWWWMw!                                    ")
	fmt.Println("                            !9WWWWWWU>`>&WWWWWWUH!_JNWWWWWQz  ^EWWWWg|                                  ")
	fmt.Println("                           _SWWWWWNe: /RWWWWWWNNHBRuyix&WWWWWg2?-\"VNWWW6_                              ")
	fmt.Println("                         \"kWWWWWNz. .zNWWWWWWw=, ^NsLQNW**MWWWW&WQJuNWWWNr.                            ")
	fmt.Println("                       .FNWWWWNu. rL&WWWWWWg!!*;^Jo!*BN0aFx)>|!;;;;;!~/r)xFwaao?|,                      ")
	fmt.Println("                     .sNWWWWMi` -,#WWWWWWNi\"` Siwu UWv  .;^|^;`               .!*lUSF*;                ")
	fmt.Println("                    )BWWWWWo.   9NWWWWWW0; ;PvLc*aU&^ |L=-``.;>*=                   ;)wmkL_             ")
	fmt.Println("                  _QWWWWWq\"   .aWWWWWWWs`  rF<>/^gQ, /i   ,;;.  !2                      ,*k0F/`        ")
	fmt.Println("                 *NWWWWNv   ,/&WWWWWWNr \"!SL92l)BU.  ^x   x. L,  I_                        `>P&F;      ")
	fmt.Println("               `2WWWWWg;    !BWWWWWWD\"   .s;!/xNa     /L,   !L`  P,                           .?&gr     ")
	fmt.Println("              ,QWWWWWS`  >;LWWWWWWWk`_;!/u|  ^Ml        ;~!^,  `iv                              `?Ng^   ")
	fmt.Println("             ^BWWWWWi   *i7NWWWWWWc \"a;;?ii\"~NV             `;?},                                 ,9WF  ")
	fmt.Println("            >WWWWWB!  ` ;8WWWWWWM=  r>`;F/2wNc          .;||!,                                      oW#.")
	fmt.Println("           ?WWWWW#\"  `2;7NWWWWW&_ =_=u%ir`>Wi                                                        PW6")
	fmt.Println("          rWWWWWc   `||>WWWWWWU.  r^?7;!v*W)                                                         ,WW|")
	fmt.Println("         ^NWWWB!  ! /jrmWWWWWw  `vL.k*/vkW$>rr*r;`        ;rL{7)>!`                                   mWF")
	fmt.Println("         .BWWW$,   ,u. PWWWWW) ,r`)|)!__LWv     `;L\"     |s>:```._|JuL                                 qWE")
	fmt.Println("        uWWWH` .vi\"Fo*WWWWN>   ^v  r*`>W}                                                             &Ws ")
	fmt.Println("        ;WWWP`  `=*ox_pWWWB; ^)i`9xr,#7W*            .     ,/*`                                       |WW!")
	fmt.Println("       SWWD` >LLr^_y*NWWQ\"  ,<?P~|iF0W}            ~;   v_ `o;                                      .0WU")
	fmt.Println("      ^WW0,.!F2xULFi5WW0` >7vr!!z_`*Wv             `|;;^!,~!`                                      .8W8.")
	fmt.Println("      dWN;`>JyrkIr`!NWN! ,uFia!9?*2WI                                                             ;QWD.")
	fmt.Println("     =WW7`_S)~Fxv| xWWi ;}drqa=;=uWRNmL,                                                         rWWt`")
	fmt.Println("     DWP`;LiL;}c*rsWW&`,Po_e7L/ =Nc `>oD$aawTouic7)*r>=|^^~!;;;;;;;;;;;;;~^/>rvL{JctxiiiiuusoF2kgBS/ ")
	fmt.Println("    ;WN\\Uy>*rF.,pWWWr-;?J}\"vov^^Nu         `.,\"_;!~^/=>r*v?LL{}Jjjjjjj}}7?vr>/^!;____-\"\"\",,,..``    ")
	fmt.Println("    iW?_**>^;>\"~&EeWg=|liv*s!~?NL")
	fmt.Println("    wWc*$>*~~L6Ni QW! /Uursx >WJ")
	fmt.Println("    2M)o*_F \"R0; .Wd~U7,``;*iN>")
	fmt.Println("    xWe?vI7cMu`  ,W&>xssr~=PB|")
	fmt.Println("    \"WY ,cBZ_    `M2l//i,,QQ,")
	fmt.Println("     |U$di_       UBu>i)yBy`")
	fmt.Println("                  ^Wx,rDR!")
	fmt.Println("                   /ZUl^")
	fmt.Println(".oPYo. .oPYo. .pPYo.   .oPYo.                       o   o                 .oPYo.   o              8  o                ")
	fmt.Println("8  .o8     `8 8        8    8                       8                     8        8              8                   ")
	fmt.Println("8 .P`8   .oP` 8oPYo.   8      oPYo. .oPYo. .oPYo.  o8P o8 o    o .oPYo.   `Yooo.  o8P o    o .oPYo8 o8 .oPYo. .oPYo.  ")
	fmt.Println("8.d` 8    `b. 8`  `8   8      8  `` 8oooo8 .oooo8   8   8 Y.  .P 8oooo8       `8   8  8    8 8    8  8 8    8 Yb..   ")
	fmt.Println("8o`  8     :8 8.  .P   8    8 8     8.     8    8   8   8 `b..d` 8.            8   8  8    8 8    8  8 8    8   `Yb. ")
	fmt.Println("`YooP` `YooP` `YooP`   `YooP` 8     `Yooo` `YooP8   8   8  `YP`  `Yooo`   `YooP`   8  `YooP` `YooP`  8 `YooP` `YooP. ")
	fmt.Println(":.....::.....::.....::::.....:..:::::.....::.....:::..::..::...:::.....::::.....:::..::.....::.....::..:.....::.....:")
	fmt.Println(":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::")
	fmt.Println(":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::")
}