name: efitoggler
description: efitoggler
version: 1.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  colorize: ^3.0.0
  console: ^4.1.0
  interact: ^2.1.1

dev_dependencies:
  lints: ^2.0.0