#!/usr/bin/env bash

SUDO=
if [ "$EUID" != "0" ]; then
	if  [ -e /usr/bin/sudo ] || [ -e /bin/sudo ]; then
		SUDO=sudo
	else
		echo "ERROR: En este sistema no existe el binario de superusuario."
		exit 0
	fi
fi

rm /tmp/source.sh* 2> /dev/null
rm /tmp/dest.sh* 2> /dev/null
SOURCETEMP=/tmp/source.sh.$$
DESTTEMP=/tmp/dest.sh.$$

SOURCE=""
DEST=""

function cleanup { rm "$SOURCE"; rm "$DEST"; exit; }

trap cleanup; SIGHUP SIGINT SIGTERM

function core { clear; cover; sleep 1s; verify; }

function cover {
	echo '          					    ``...`                                                    '
	echo '                                      `..:/+++/--/shdmmmmmhy+:.`                                              '
	echo '                                  `-+ydmMMMMMMMMMMMMMMMMMMMMMMNds:`                                           '
	echo '                               `/ymMMMMMNmNMMMMMMMMMMMMNhooyNNMMMMmy:`                                        '
	echo '                             -yNMMMMMNy//hMMMMMMMNyymMMMMNdhm-:sNMMMMd/                                       '
	echo '                           .yMMMMMMNo.`oMMMMMMMMod: .ydMMMMMM+.``omMMMMh.                                     '
	echo '                         `oNMMMMMMo` -MMMMMMMMMmdmMNNmyNMMMMMMMNy/`oNMMMN/                                    '
	echo '                        /mMMMMMMs.  oMMMMMMMNo.  :Mo:hMMs:mMMMMNMMmyhMMMMMo-`                                  '
	echo '                      -hMMMMMMy. .sdMMMMMMMh.o/-/sy:+NMNhys+/:-......--:/+oshddyo/-`                           '
	echo '                    `sNMMMMMh: ` +MMMMMMMMo` .dshs yMh.` `.-..               ``-/oydds/.                       '
	echo '                   /mMMMMMm/`  odMMMMMMMm- s::ydomsMy``+o+:-:/++/`                 `./sdds/.                   '
	echo '                 `yMMMMMMs`   -mMMMMMMMh.  +y+/:-hMs `h-       `:y.                    `.+hmh+.               '
	echo '                -dMMMMMm:  `.:NMMMMMMMs` ./hyso/dMo  :y   //:/-  :y                        ./hmh/`            '
	echo '               :mMMMMMd.   `+NMMMMMMN+ .-ohyyhhhMo   `h.  :: `y   N                           .odmo.           '
	echo '              +NMMMMMy`  `./NMMMMMMN/   `+/-:/yMo     .o:.`.-+-  -d                             `/dNs.        '
	echo '             oMMMMMMs`  o-+MMMMMMMN:`::/oo-  +Ms        -----`  -y-                               `oNm/       '
	echo '           `sMMMMMMo   +yoNMMMMMMm-`o/`-oyh`+Ms          `````-oo`                                  -dMy`     '
	echo '          `yMMMMMN/    /yNMMMMMMd. -h--h+-ysMy          `-////:`                                     `dMh`    '
	echo '          yMMMMMN:  -+:oMMMMMMMd````y++o++sNh`                                                        `mMy    '
	echo '        /MMMMMy`   /+ooMMMMMMh`  ./+N:-+oNm`                                                            mMd   '
	echo '       .NMMMMs  `+ +++MMMMMMy   so++s++oNNs+oooo/-       `/oysyyso/.                                    yMM   '
	echo '       dMMMM+    :s `mMMMMMs `o +++o.-:mN.     `-o-     -h+-`   `-/sh+                                  yMM   '
	echo '      /MMMM+  -/o msoMMMMMo   :y `-s-`dN-                            `                                  hMN    '
	echo '      dMMM+   +oooy:mMMMMo ./o`do:+y/yM/                  `:/`                                         `NMh    '
	echo '     /MMMs  --:+s+osMMMM+  :sy/d//+hNM+            `/   .  `:y                                         sMM:    '
	echo '     mMMd` .mss+`hoyMMM+  `./ss++oohMo             .+  `y+/:+:                                        :MMy     '
	echo '    /MMN. o+mhym/yyNMMs  syo+./y. +Ny               -:::. ``                                         :NMd`     '
	echo '    dMM/`-ysoshh.`+MMm``-yhhdohysyMM:                                                               /NMd.      '
	echo '   :MMy.-sd:oy+y.`dMM/ :od+dhs./oNmmNh/.                                                          `oMMs`      '
	echo '   yMN.-/oy.+yys-hMMd -hy:yy+o `dm.`/ymdyysooo+///::--.......................--::////////+++++oooshNmo   	    '
	echo '  `MMy/+yyosy/-/dMMM/:/ss-oys/`dN-    `.--:://++ooosssyyyyyhyyyyhhhhhhhyyyhyyyssoo++++++///////::::-`         '
	echo '  +Mm`.+dy+sy.-mmNMm`.oys/yyo+hN:                                                                             '
	echo '  yMo/m+.`.-o/Nd-MMo+hho:oh``yM/                                                                               '
	echo '  hMd+ysy+:/yMy`:Mm :+ysoo+ yM/                                                                                '
	echo '  yM/h+-h``hMo  +My+d:`- :syM+                                                                                '
	echo '  oMds+ms+Nm-   +Mm/yyd//:hM/                                                                                  '
	echo '  -Mh  :dNs`    /Mod+:h``dN:                                                                                  	'
	echo '   oNdmms.      -Mmhody/mm-                                                                                    '
	echo '    .--`         mN. -yMy.                                                                                     '
	echo '                  /Nhsmd/                                                                                       '
	echo '                  -/+-`                     '
	echo '                                                                                                                     '
	echo '.oPYo. .oPYo. .pPYo.   .oPYo.                       o   o                 .oPYo.   o              8  o                '
	echo '8  .o8     `8 8        8    8                       8                     8        8              8                   '
	echo '8 .P`8   .oP` 8oPYo.   8      oPYo. .oPYo. .oPYo.  o8P o8 o    o .oPYo.   `Yooo.  o8P o    o .oPYo8 o8 .oPYo. .oPYo.  '
	echo '8.d` 8    `b. 8`  `8   8      8  `` 8oooo8 .oooo8   8   8 Y.  .P 8oooo8       `8   8  8    8 8    8  8 8    8 Yb..   '
	echo '8o`  8     :8 8.  .P   8    8 8     8.     8    8   8   8 `b..d` 8.            8   8  8    8 8    8  8 8    8   `Yb. '
	echo '`YooP` `YooP` `YooP`   `YooP` 8     `Yooo` `YooP8   8   8  `YP`  `Yooo`   `YooP`   8  `YooP` `YooP`  8 `YooP` `YooP. '
	echo ':.....::.....::.....::::.....:..:::::.....::.....:::..::..::...:::.....::::.....:::..::.....::.....::..:.....::.....:'
	echo ':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'
	echo ':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'
}

function whichverify() {
	stat=$(which "$1" 2>&1)
	if [[ "$stat" =~ ^which:* ]]; then 
		return 1
	else
		return 0
	fi
}

function syncer {

	SOURCEREADY=""
	DESTREADY=""

    if [[ "$SOURCE" =~ .*\/$ ]]; then
        SOURCEREADY="$SOURCE"
    else
        SOURCEREADY="$SOURCE/"
    fi

    if [[ "$DEST" =~ .*\/$ ]]; then
        DESTREADY="$DEST"
    else
        DESTREADY="$DEST/"
    fi

	clear
	echo -e "=============== EMPEZAR RSYNC =============== \n" 
	echo "SOURCE: $SOURCEREADY"
	echo -e "DESTINATION: $DESTREADY \n"
	$SUDO rsync -axHAWXS --numeric-ids --info=progress2 "$SOURCEREADY" "$DESTREADY"

	echo -e "\n =============== OK =============== \n" 
	echo -e "Listo!\n"
	exit 0
}

function validator() {

	if [ "$1" == "source" ]; then
		if [ "$2" != "" ]; then
			if [ -d "$2" ]; then
				SOURCE="$2"
				destiaction
				return 0
			else
				clear
    			echo "ERROR: El directorio \"$2\" no existe"
        	    read -r -p "Presione Enter para continuar..."
        		sourceaction
				return 0
			fi
		else
			exit 0;
		fi
	elif [ "$1" == "dest" ]; then
		if [ "$2" != "" ]; then
			if [ -d "$2" ]; then
				DEST="$2"
				syncer
				return 0
			else
				clear
    			echo "ERROR: El directorio \"$2\" no existe"
        		read -r -p "Presione Enter para continuar..."
        		destiaction
				return 0
			fi
		else
			sourceaction
		fi
	else
		exit 0;
	fi
	
}

function sourceaction {

    dialog --title "036 rsyncer" \
    --backtitle "036 Creative Studios" \
    --inputbox "Por favor escriba su directorio de origen" 8 80 2>"$SOURCETEMP"

    RESPONSE=$?
    DATA=$(<$SOURCETEMP)

    case $RESPONSE in
    0) 
        validator "source" "${DATA}" ;;
    1) 
        clear; exit 0  
        return;;
    255) 
        clear; exit 0
        return;;
    esac

}

function destiaction {

	RESPONSE=0
	DATA=0

	dialog --title "036 rsyncer" \
	--backtitle "036 Creative Studios" \
	--inputbox "Por favor escriba su directorio de destino" 8 80 2>"$DESTTEMP"

	RESPONSE=$?
	DATA=$(<$DESTTEMP)

	case $RESPONSE in
	0) 
		validator "dest" "${DATA}" ;;
	1) 
		clear; sourceaction break;;
	255) 
		clear; sourceaction break;;
	esac

}

function verify {

    OPERATING=$(uname -o)
	SELECTOR=""

	if [ "$OPERATING" != "GNU/Linux" ]; then
		echo "ERROR: Este sistema no es GNU/Linux, saliendo"
		exit 0
	fi

	SELECTOR="rsync"
	whichverify "$SELECTOR"
	local res=$?

	if [ $res -eq 1 ]; then
		echo "ERROR: El ejecutable de rsync, no se encuentra en el sistema, por favor instalalo"
		exit 0
	fi

	echo "Todo ok!"

	START=$(date +%s)
	CHARS="/-\|"

	while [[ $(($(date +%s) - START)) -lt 2 ]]; do
		for (( i=0; i<${#CHARS}; i++ )); do
			sleep 0.08
			echo -en "${CHARS:$i:1}" "\r"
		done
	done
	clear

    sourceaction
}

core

[ -f $SOURCETEMP ] && rm $SOURCETEMP
[ -f $DESTTEMP ] && rm $DESTTEMP