name: usb_manager_gui
description: usb_manager_gui

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  adwaita: ^1.0.1
  async: ^2.11.0
  bitsdojo_window: ^0.1.5
  flutter:
    sdk: flutter
  flutter_platform_alert: ^0.4.0
  flutter_riverpod: ^2.3.6
  fpdart: ^1.0.0
  libadwaita: ^2.0.2
  libadwaita_bitsdojo: ^0.5.5
  niku: ^2.4.2
  shared_preferences: ^2.2.0
  zerothreesix_dart: ^0.0.4

dependency_overrides:
  file: 7.0.0
  win32: 5.0.6

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
