name: usb_manager_gui
description: usb_manager_gui

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adwaita: ^0.5.2
  async: ^2.11.0
  bitsdojo_window: ^0.1.5
  flutter_platform_alert: ^0.4.0
  flutter_riverpod: ^2.3.6
  fpdart: ^0.6.0
  get_it: ^7.6.0
  injectable: ^2.1.1
  libadwaita: ^1.2.5
  libadwaita_bitsdojo: ^0.5.5
  niku: ^2.3.3
  riverpod_context: ^0.3.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/
