name: usb_manager_gui
description: usb_manager_gui

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adwaita: ^0.5.2
  async: ^2.10.0
  bitsdojo_window: ^0.1.5
  conditioned: ^0.1.0-dev.1
  flutter_platform_alert: ^0.3.0
  flutter_riverpod: ^2.1.3
  fpdart: ^0.4.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  libadwaita: ^1.2.5
  libadwaita_bitsdojo: ^0.5.5
  nester: ^1.2.1
  niku: ^2.3.3
  riverpod_context: ^0.3.0
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/
