name: usb_manager_gui
description: usb_manager_gui

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  adwaita: ^1.1.0
  async: ^2.11.0
  bitsdojo_window: ^0.1.6
  flutter:
    sdk: flutter
  flutter_platform_alert: ^0.5.1
  flutter_riverpod: ^2.4.9
  fpdart: ^1.1.0
  libadwaita: ^2.0.2
  libadwaita_bitsdojo: ^0.5.5
  niku: ^2.4.3
  shared_preferences: ^2.2.2
  zerothreesix_dart: ^0.0.6+11

dependency_overrides:
  win32: ^5.2.0

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
