name: ext4_optimizer
description: ext4_optimizer
version: 1.0.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cli_menu: ^0.4.0+1
  fpdart: ^1.1.0
  zerothreesix_dart: ^0.1.3

dev_dependencies:
  lints: ^3.0.0
