name: usb_manager
description: usb_manager
version: 1.0.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  cli_menu: ^0.4.0+1
  fpdart: ^1.1.0
  get_it: ^7.7.0
  injectable: ^2.4.4
  zerothreesix_dart: ^0.1.5

dependency_overrides:
  win32: 5.5.3

dev_dependencies:
  build_runner: ^2.4.11
  coverage: ^1.9.0
  custom_lint: ^0.6.4
  dart_code_linter: ^1.1.3
  import_sorter: ^4.6.0
  injectable_generator: ^2.6.2
  lints: ^4.0.0
  mocktail: ^1.0.4
  pyramid_lint: ^2.0.0
  remove_from_coverage: ^2.0.0
  test: ^1.25.8

import_sorter:
  comments: false
