name: rsyncer_cli
description: rsyncer_cli
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  console: ^4.1.0
  dcli: ^3.0.2
  zerothreesix_dart: ^0.0.5

dev_dependencies:
  lints: ^2.1.1
