name: zerothreesix_flutter
description: victor7w7r utils collection for flutter
version: 0.2.12
homepage: 'https://github.com/victor7w7r/'

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  barcode_widget: ^2.0.4
  bitsdojo_window: ^0.1.5
  dart_ipify: ^1.1.1
  dio: ^5.3.0
  flash: ^3.0.5+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_web_plugins:
    sdk: flutter
  fpdart: ^1.0.0
  functional_widget_annotation: ^0.10.0
  go_router: ^10.0.0
  graphql: ^5.1.3
  json_annotation: ^4.8.1
  niku: ^2.4.2
  path_provider: ^2.0.15
  platform_device_id: ^1.0.1
  share_plus: ^7.0.2
  tailwind_colors: ^0.3.1
  universal_html: ^2.2.3

dependency_overrides:
  intl: 0.18.1
  win32: 5.0.6

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  functional_widget: ^0.10.1
  source_gen: ^1.4.0

flutter: