name: rsyncer_gui
description: rsyncer_gui

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adwaita: ^1.0.1
  bitsdojo_window: ^0.1.5
  file_picker: ^5.3.3
  flutter_platform_alert: ^0.4.0
  flutter_pty: ^0.4.0
  flutter_riverpod: ^2.3.6
  fpdart: ^1.0.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  libadwaita: ^2.0.2
  libadwaita_bitsdojo: ^0.5.5
  niku: ^2.4.2
  riverpod_context: ^0.3.0
  shared_preferences: ^2.2.0
  xterm: ^3.5.0

dependency_overrides:
  win32: 5.0.6

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true

  assets:
    - assets/
