name: "main"
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: write
jobs:
  maccompile:
    name: Compile EfiToggler for macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Compile CLI
        run: |
          cd efitoggler
          mkdir dist
          dart pub get
          dart compile exe bin/efitoggler.dart -o efitoggler
          mv efitoggler dist
      - uses: actions/upload-artifact@v4
        with:
          name: bin-efitoggler
          path: efitoggler/dist
  linuxcompile:
    needs: maccompile
    name: Compile all linux utilites
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Compile Apps
        run: |
          mkdir rsyncer/dist
          mkdir ext4_optimizer/dist
          mkdir usb_manager/dist
          cd rsyncer
          dart pub get
          dart compile exe bin/rsyncer.dart -o rsyncer
          mv rsyncer dist
          cd ../ext4_optimizer
          dart pub get
          dart compile exe bin/ext4_optimizer.dart -o ext4_optimizer
          mv ext4_optimizer dist
          cd ../usb_manager
          dart pub get
          dart compile exe bin/usb_manager.dart -o usb_manager
          mv usb_manager dist
      - uses: actions/upload-artifact@v4
        with:
          name: bin-rsyncer
          path: rsyncer/dist
      - uses: actions/upload-artifact@v4
        with:
          name: bin-ext4_optimizer
          path: ext4_optimizer/dist
      - uses: actions/upload-artifact@v4
        with:
          name: bin-usb_manager
          path: usb_manager/dist
  release:
    needs: linuxcompile
    name: Release to Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: bin-efitoggler
          path: bin-ef
      - uses: actions/download-artifact@v4
        with:
          name: bin-rsyncer
          path: bin-rsy
      - uses: actions/download-artifact@v4
        with:
          name: bin-ext4_optimizer
          path: bin-ext
      - uses: actions/download-artifact@v4
        with:
          name: bin-usb_manager
          path: bin-usb
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: bin-*/*
